Feature/CN-5514 margin call flow
CelsiusNetwork/celsius-app pull request #1026
Opened 2020-09-21 09:22 UTC by ShamanShaulic

## Checklist (Mandatory):

- [ ] I have named the PR correctly (Check PR1)
- [ ] Check the commit’s or even all commits message styles matches our requested structure. (issue number, etc.) (Check CR10)
- [ ] I have tested new code locally (Check CR3)
- [ ] I have done a smoke test of the larger feature locally (Check CR3)
- [ ] I have added at least two reviewers (Check PR5)
- [ ] I have assigned the PR to myself (Check PR4)
- [ ] I have merged develop (parent) branch into my feature branch and resolved all conflicts (Check PR7)

## Checklist (Optional):

- [ ] I have added necessary documentation, including instructions how to test (Check CR8)
- [ ] I have added tests that prove my fix/implementation is effective or that my feature works
- [ ] I have written the code according to the adopted style guide? (Check CR7)

## Additional notes

> What does this implement/fix? Explain your changes. (optional)
> Are there any scripts that need running (eg. yarn install)?
> Are there any edge cases that need checking?
> Are there any specific test instructions?

[MVPWorkshop Pull Request & Code Review Guidelines](https://docs.google.com/document/d/1TcuU1JBhlGZLtpy0osSNinXQ2piP_yrDuRcXdqaOS_U/edit#heading=h.5b6kpdr4btq8)

2020-09-23 13:32 UTC, fjovakaric requested changes

2020-09-23 13:32 UTC, fjovakaric commented on app/components/modals/LoanAlertsModals/LoanAlertsPayoutPrincipalModal/LoanAlertsPayoutPrincipalModal.js
> +          {/* <CelModalButton*/}
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/modals/LoanAlertsModals/LoanAlertsPayoutPrincipalModal/LoanAlertsPayoutPrincipalModal.js
> -LoanAlertsPayoutPrincipalModal.propTypes = {
why is this removed?

2020-09-23 13:32 UTC, fjovakaric commented on app/components/modals/LoanApplicationSuccessModal/LoanApplicationSuccessModal.js
> +  // setupAutomaticInterestPayment = async m => {
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/modals/MarginCallConfirmModal/MarginCallConfirmModal.styles.js
> +    card: { color: "#F3F3F3" },
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/modals/MarginCallConfirmModal/MarginCallConfirmModal.styles.js
> +    card: { color: STYLES.COLORS.MEDIUM_GRAY },
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/CollateralCoinCard/CollateralCoinCard.js
> +                    fill={STYLES.COLORS.CELSIUS_BLUE}
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/CollateralCoinCard/CollateralCoinCard.js
> +                  <CelText color={STYLES.COLORS.CELSIUS_BLUE} type={"H5"}>
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/CollateralLoanCard/CollateralLoanCard.js
> +      if (transaction.loan_data.status === "rejected") {
move to loan statuses constant

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/LoanCard/LoanCard.js
> +        interestAmount: props.transaction.loan_data.loan_amount,
don't use `props.` use `{ transaction } = props`

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/LoanCard/LoanCard.js
> +          color: STYLES.COLORS.CELSIUS_BLUE,
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/LtvCard/LtvCard.js
> +  set = () => {
unused method

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/PaymentCard/PaymentCard.js
> +    reason: PropTypes.oneOf(
move to constants

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/PaymentCard/PaymentCard.js
> +            actions.navigateTo("Deposit", {
SCREENS.DEPOSIT

2020-09-23 13:32 UTC, fjovakaric commented on app/components/molecules/PaymentCard/PaymentCard.js
> +            onPress={() => actions.navigateTo("Deposit", { coin: coin.short })}
SCREENS.DEPOSIT

2020-09-23 13:32 UTC, fjovakaric commented on app/components/organisms/LoanOverviewCard/LoanOverviewCard.js
> +            {/* <CelButton*/}
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/organisms/LoanOverviewCard/LoanOverviewCard.js
> +                      <CelText align={"left"} type={"H3"} weight={"600"}>
is left alignment is default?

2020-09-23 13:32 UTC, fjovakaric commented on app/components/organisms/LoanOverviewCard/LoanOverviewCard.js
> +                      navigateTo("ChoosePaymentMethod", {
use SCREENS

2020-09-23 13:32 UTC, fjovakaric commented on app/components/organisms/TierCard/TierCard.js
> +      color = STYLES.COLORS.GRAY;
use new colors in the component

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/BorrowLoanTerm/BorrowLoanTerm.js
> +            // actions.navigateTo("BorrowLoanConfirm");
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/ChoosePaymentMethod/ChoosePaymentMethod.js
> +      <CelSwitch
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/ExtendLoanScreen/ExtendLoanScreen.js
> +              formData.extendPeriod === m ? STYLES.COLORS.CELSIUS_BLUE : null
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/InterestPaymentOverviewScreen/InterestPaymentOverviewScreen.js
> +                    color={COLOR_KEYS.NEGATIVE_STATE}
do we need getColor?

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/InterestPaymentOverviewScreen/InterestPaymentOverviewScreen.js
> +                    actions.navigateTo("ChoosePaymentMethod", {
use SCREENS

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/LoanPaymentCoin/LoanPaymentCoin.js
> +      // actions.navigateTo(SCREENS.VERIFY_PROFILE, {
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/LoanPrepaymentPeriod/LoanPrepaymentPeriod.js
> +        // actions.navigateTo(SCREENS.VERIFY_PROFILE, {
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/LoanSettings/LoanSettings.js
> +        {/* <IconButton*/}
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/MarginCallOverviewScreen/MarginCallOverviewScreen.styles.js
> +    card: { color: "#F3F3F3" },
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/SingleMarginCallScreen/SingleMarginCallScreen.styles.js
> +    card: { color: "#F3F3F3" },
use new colors

2020-09-23 13:32 UTC, fjovakaric commented on app/components/screens/TransactionsIntersection/TransactionsIntersection.js
> +    const hide = navigation.getParam("hideBack");
what was wrong with the previous code?

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/loans/loansActions.js
> +        navigateTo("LoanRequestDetails", {
use SCREENS

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/loans/loansActions.js
> +      // dispatch(
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/loans/loansActions.js
> +      // if (
remove comments

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/loans/loansActions.js
> +      dispatch(navigateTo("BorrowLanding"));
use screens

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/loans/loansActions.js
> +      dispatch(
add dispatch success action for api call

2020-09-23 13:32 UTC, fjovakaric commented on app/redux/user/userDataActions.js
> +      // dispatch(navigateTo(SCREENS.CONFIRM_YOUR_LOAN));
use SCREENS

2020-09-23 13:32 UTC, fjovakaric commented on app/utils/loanPayment-util.js
> +function calculateAdditionalPayment(
valjda radi, srecno sa testovima

2020-09-24 06:52 UTC, ShamanShaulic commented on app/components/modals/LoanAlertsModals/LoanAlertsPayoutPrincipalModal/LoanAlertsPayoutPrincipalModal.js
> +          {/* <CelModalButton*/}
This should be uncommented any time now

2020-09-24 08:15 UTC, fjovakaric approved these changes

2020-09-24 09:29 UTC, merged