CN-8589: Implement warning message
CelsiusNetwork/celsius-app pull request #1156
Opened 2020-11-10 14:59 UTC by wp-ilija-vucetic

## Checklist (Mandatory):

- [x] I have named the PR correctly (Check PR1)
- [x] Check the commit’s or even all commits message styles matches our requested structure. (issue number, etc.) (Check CR10)
- [x] I have tested new code locally (Check CR3)
- [x] I have done a smoke test of the larger feature locally (Check CR3)
- [x] I have added at least two reviewers (Check PR5)
- [x] I have assigned the PR to myself (Check PR4)
- [x] I have merged develop (parent) branch into my feature branch and resolved all conflicts (Check PR7)

## Checklist (Optional):

- [ ] I have added necessary documentation, including instructions how to test (Check CR8)
- [ ] I have added tests that prove my fix/implementation is effective or that my feature works
- [ ] I have written the code according to the adopted style guide? (Check CR7)

## Additional notes

> What does this implement/fix? Explain your changes. (optional)
> Are there any scripts that need running (eg. yarn install)?
> Are there any edge cases that need checking?
> Are there any specific test instructions?

[MVPWorkshop Pull Request & Code Review Guidelines](https://docs.google.com/document/d/1TcuU1JBhlGZLtpy0osSNinXQ2piP_yrDuRcXdqaOS_U/edit#heading=h.5b6kpdr4btq8)

2020-11-12 10:55 UTC, CrnogoracIvan requested changes
From comments.

2020-11-12 10:55 UTC, CrnogoracIvan commented on app/components/screens/HODLViewCode/HODLViewCode.js
> +                                   imageStyle={{ borderRadius: 6 }}
Move borderRadius to style

2020-11-12 10:55 UTC, CrnogoracIvan commented on app/components/screens/HODLViewCode/HODLViewCode.js
> +              <TouchableOpacity
Maybe TouchableWithoutFeedback?

2020-11-12 10:55 UTC, CrnogoracIvan commented on app/components/screens/HODLViewCode/HODLViewCode.js
> +          <InfoBox
Move to renderInfoBox function

2020-11-12 10:55 UTC, CrnogoracIvan commented on app/components/screens/HODLViewCode/HODLViewCode.js
> +                {this.state.showHodlCodeOverlay &&
Maybe ternary here?

2020-11-12 10:55 UTC, CrnogoracIvan commented on app/components/screens/TwoFactorSettings/TwoFactorSettings.js
>          <Card styles={{ alignItems: "center", marginTop: 25 }}>
Move to styles.

2020-11-16 08:44 UTC, fjovakaric approved these changes

2020-11-16 08:44 UTC, fjovakaric commented on app/components/screens/HODLViewCode/HODLViewCode.js
> +  function;
?

2020-11-16 08:47 UTC, merged